package labels

var frFR = &LabelSet{
		Sections: map[string]string{
			"1": "Installation et correctifs",
			"2": "Permissions des répertoires et fichiers",
			"3": "Journalisation et audit",
			"4": "Accès utilisateur et autorisation",
			"5": "Connexion et authentification",
			"6": "Paramètres PostgreSQL",
			"7": "Réplication",
			"8": "Considérations de configuration spéciales",
		},
		Checks: map[string]CheckLabel{
			"1.1":   {Title: "S'assurer que les paquets proviennent de dépôts autorisés", Manual: true},
			"1.1.1": {Title: "S'assurer que les paquets proviennent du PGDG"},
			"1.2":   {Title: "Installer uniquement les paquets nécessaires", Manual: true},
			"1.3":   {Title: "S'assurer que les fichiers de service systemd sont activés"},
			"1.4":   {Title: "S'assurer que le cluster de données a été initialisé avec succès"},
			"1.4.1": {Title: "Vérifier l'initialisation du PGDATA"},
			"1.4.2": {Title: "Vérifier la version dans PGDATA"},
			"1.4.3": {Title: "S'assurer que les checksums sont activés"},
			"1.4.4": {Title: "S'assurer que les WAL et fichiers temporaires sont sur une partition séparée"},
			"1.4.5": {Title: "S'assurer que la partition PGDATA est chiffrée", Manual: true},
			"1.5":   {Title: "S'assurer que PostgreSQL est à jour"},
			"1.6":   {Title: "Vérifier que PGPASSWORD n'est pas défini dans les profils"},
			"1.7":   {Title: "Vérifier que PGPASSWORD n'est pas dans l'environnement"},
			"1.8":   {Title: "S'assurer que les extensions installées sont autorisées"},
			"1.9":   {Title: "S'assurer que les emplacements des tablespaces sont sécurisés"},
			"2.1":   {Title: "S'assurer que le masque de permissions est correct"},
			"2.2":   {Title: "S'assurer de l'appartenance au groupe pg_wheel"},
			"2.3":   {Title: "S'assurer que l'historique psql n'est pas conservé"},
			"2.4":   {Title: "S'assurer que .pg_service.conf ne contient pas de mots de passe"},
			"2.5":   {Title: "S'assurer que les permissions de pg_hba.conf sont restrictives"},
			"2.6":   {Title: "S'assurer que le socket Unix a des permissions restrictives"},
			"2.7":   {Title: "S'assurer que PGDATA a des permissions restrictives"},
			"2.8":   {Title: "S'assurer que le contenu de PGDATA appartient à postgres", Manual: true},
			"3.1.2":  {Title: "S'assurer que les destinations de log sont correctes"},
			"3.1.3":  {Title: "S'assurer que le collecteur de logs est activé"},
			"3.1.4":  {Title: "S'assurer que le répertoire de logs est correct"},
			"3.1.5":  {Title: "S'assurer que le modèle de nom de fichier de log est correct"},
			"3.1.6":  {Title: "S'assurer que les permissions des fichiers de log sont correctes"},
			"3.1.7":  {Title: "S'assurer que log_truncate_on_rotation est activé"},
			"3.1.8":  {Title: "S'assurer que la durée de vie maximale des fichiers de log est correcte"},
			"3.1.9":  {Title: "S'assurer que la taille maximale des fichiers de log est correcte"},
			"3.1.10": {Title: "S'assurer que la facilité syslog est correcte"},
			"3.1.11": {Title: "S'assurer que syslog_sequence_numbers est activé"},
			"3.1.12": {Title: "S'assurer que syslog_split_messages est activé"},
			"3.1.13": {Title: "S'assurer que syslog_ident est correct"},
			"3.1.14": {Title: "S'assurer que log_min_messages est correct"},
			"3.1.15": {Title: "S'assurer que les messages d'erreur sont correctement écrits"},
			"3.1.16": {Title: "S'assurer que debug_print_parse est désactivé"},
			"3.1.17": {Title: "S'assurer que debug_print_rewritten est désactivé"},
			"3.1.18": {Title: "S'assurer que debug_print_plan est désactivé"},
			"3.1.19": {Title: "S'assurer que debug_pretty_print est activé"},
			"3.1.20": {Title: "S'assurer que log_connections est activé"},
			"3.1.21": {Title: "S'assurer que log_disconnections est activé"},
			"3.1.22": {Title: "S'assurer que le préfixe de ligne de log est correct"},
			"3.1.23": {Title: "S'assurer que log_statement est correct"},
			"3.1.24": {Title: "S'assurer que log_timezone est correct"},
			"3.1.25": {Title: "S'assurer que log_error_verbosity est correct"},
			"3.1.26": {Title: "S'assurer que log_hostname est désactivé"},
			"3.1.27": {Title: "S'assurer que log_duration est désactivé"},
			"3.2":    {Title: "S'assurer que l'extension pgAudit est activée"},
			"4.1":  {Title: "S'assurer que sudo est utilisé pour l'accès admin postgres"},
			"4.3":  {Title: "S'assurer que les privilèges administratifs excessifs sont révoqués"},
			"4.4":  {Title: "S'assurer que les rôles de connexion ont des mots de passe forts"},
			"4.5":  {Title: "S'assurer que les fonctions SECURITY DEFINER sont sécurisées"},
			"4.6":  {Title: "S'assurer que les privilèges DML excessifs sont révoqués"},
			"4.7":  {Title: "S'assurer que la sécurité au niveau des lignes est configurée"},
			"4.8":  {Title: "S'assurer que l'extension set_user est installée"},
			"4.9":  {Title: "S'assurer qu'une extension de chiffrement est installée"},
			"4.10": {Title: "S'assurer que le schéma public a des privilèges appropriés"},
			"5.1":  {Title: "S'assurer que la connexion locale est configurée correctement"},
			"5.2":  {Title: "S'assurer que listen_addresses est configuré correctement"},
			"5.3":  {Title: "S'assurer que les connexions locales utilisent une authentification sécurisée"},
			"5.4":  {Title: "S'assurer que les connexions hôte utilisent une authentification sécurisée"},
			"5.5":  {Title: "S'assurer que les limites de connexion sont configurées"},
			"5.6":  {Title: "S'assurer que la validation de complexité des mots de passe est configurée"},
			"5.7":  {Title: "S'assurer que le délai d'authentification est configuré"},
			"5.8":  {Title: "S'assurer que SSL/GSSENC est utilisé pour toutes les connexions"},
			"5.9":  {Title: "S'assurer que les plages CIDR réseau sont minimisées"},
			"5.10": {Title: "S'assurer que les bases et utilisateurs spécifiques sont indiqués"},
			"5.11": {Title: "S'assurer que les connexions superutilisateur sont restreintes"},
			"5.12": {Title: "S'assurer que le chiffrement des mots de passe est scram-sha-256"},
			"6.2":  {Title: "S'assurer que les paramètres 'backend' sont corrects"},
			"6.3":  {Title: "S'assurer que les paramètres 'postmaster' sont corrects", Manual: true},
			"6.4":  {Title: "S'assurer que les paramètres 'sighup' sont corrects", Manual: true},
			"6.5":  {Title: "S'assurer que les paramètres 'superuser' sont corrects", Manual: true},
			"6.6":  {Title: "S'assurer que les paramètres 'user' sont corrects", Manual: true},
			"6.7":  {Title: "S'assurer que le chiffrement FIPS 140-2 est utilisé"},
			"6.8":  {Title: "S'assurer que TLS est activé et configuré correctement"},
			"6.9":  {Title: "S'assurer qu'une extension cryptographique est installée"},
			"6.10": {Title: "S'assurer que les chiffrements SSL sont corrects"},
			"6.11": {Title: "S'assurer que l'extension d'anonymisation est configurée"},
			"7.1":  {Title: "S'assurer qu'un utilisateur dédié à la réplication est configuré"},
			"7.2":  {Title: "S'assurer que les commandes de réplication sont journalisées"},
			"7.4":  {Title: "S'assurer que l'archivage WAL est configuré"},
			"7.5":  {Title: "S'assurer que les paramètres de réplication sont corrects"},
			"8.2":  {Title: "S'assurer qu'un outil de sauvegarde est configuré"},
			"8.3":  {Title: "S'assurer que la configuration des fichiers spéciaux est vérifiée"},
		},
	}
