package labels

func init() {
	RegisterLanguage("zh_CN", &LabelSet{
		Sections: map[string]string{
			"1": "安装和补丁",
			"2": "目录和文件权限",
			"3": "日志记录和审计",
			"4": "用户访问和授权",
			"5": "连接和登录",
			"6": "PostgreSQL 设置",
			"7": "复制",
			"8": "特殊配置注意事项",
		},
		Checks: map[string]CheckLabel{
			"1.1":   {Title: "确保软件包来自授权的仓库", Manual: true},
			"1.1.1": {Title: "确保软件包来自 PGDG"},
			"1.2":   {Title: "仅安装必要的软件包", Manual: true},
			"1.3":   {Title: "确保 systemd 服务文件已启用"},
			"1.4":   {Title: "确保数据集群初始化成功"},
			"1.4.1": {Title: "检查 PGDATA 的初始化"},
			"1.4.2": {Title: "检查 PGDATA 中的版本"},
			"1.4.3": {Title: "确保已启用数据校验和"},
			"1.4.4": {Title: "确保 WAL 和临时文件在单独的分区上"},
			"1.4.5": {Title: "确保 PGDATA 分区已加密", Manual: true},
			"1.5":   {Title: "确保 PostgreSQL 版本是最新的"},
			"1.6":   {Title: "验证 PGPASSWORD 未在配置文件中设置"},
			"1.7":   {Title: "验证 PGPASSWORD 未在环境变量中使用"},
			"1.8":   {Title: "确保已安装的扩展是经过授权的"},
			"1.9":   {Title: "确保表空间位置是安全的"},
			"2.1":   {Title: "确保文件权限掩码正确"},
			"2.2":   {Title: "确保 pg_wheel 组成员资格正确"},
			"2.3":   {Title: "确保 psql 命令历史未被保留"},
			"2.4":   {Title: "确保 .pg_service.conf 不包含密码"},
			"2.5":   {Title: "确保 pg_hba.conf 权限是限制性的"},
			"2.6":   {Title: "确保 Unix 套接字目录权限是限制性的"},
			"2.7":   {Title: "确保 PGDATA 目录权限是限制性的"},
			"2.8":   {Title: "确保 PGDATA 内容由 postgres 用户拥有", Manual: true},
			"3.1.2":  {Title: "确保日志目标设置正确"},
			"3.1.3":  {Title: "确保日志收集器已启用"},
			"3.1.4":  {Title: "确保日志文件目录设置正确"},
			"3.1.5":  {Title: "确保日志文件名模式设置正确"},
			"3.1.6":  {Title: "确保日志文件权限设置正确"},
			"3.1.7":  {Title: "确保 log_truncate_on_rotation 已启用"},
			"3.1.8":  {Title: "确保最大日志文件生存期设置正确"},
			"3.1.9":  {Title: "确保最大日志文件大小设置正确"},
			"3.1.10": {Title: "确保 syslog 设施设置正确"},
			"3.1.11": {Title: "确保 syslog_sequence_numbers 已启用"},
			"3.1.12": {Title: "确保 syslog_split_messages 已启用"},
			"3.1.13": {Title: "确保 syslog_ident 设置正确"},
			"3.1.14": {Title: "确保 log_min_messages 设置正确"},
			"3.1.15": {Title: "确保正确的消息写入服务器日志"},
			"3.1.16": {Title: "确保 debug_print_parse 已禁用"},
			"3.1.17": {Title: "确保 debug_print_rewritten 已禁用"},
			"3.1.18": {Title: "确保 debug_print_plan 已禁用"},
			"3.1.19": {Title: "确保 debug_pretty_print 已启用"},
			"3.1.20": {Title: "确保 log_connections 已启用"},
			"3.1.21": {Title: "确保 log_disconnections 已启用"},
			"3.1.22": {Title: "确保日志行前缀设置正确"},
			"3.1.23": {Title: "确保 log_statement 设置正确"},
			"3.1.24": {Title: "确保 log_timezone 设置正确"},
			"3.1.25": {Title: "确保 log_error_verbosity 设置正确"},
			"3.1.26": {Title: "确保 log_hostname 已禁用"},
			"3.1.27": {Title: "确保 log_duration 已禁用"},
			"3.2":    {Title: "确保已启用 pgAudit 扩展"},
			"4.1":  {Title: "确保使用 sudo 限制 postgres 管理员访问"},
			"4.3":  {Title: "确保撤销过多的管理权限"},
			"4.4":  {Title: "确保登录角色有强密码"},
			"4.5":  {Title: "确保 SECURITY DEFINER 函数已正确保护"},
			"4.6":  {Title: "确保撤销过多的 DML 权限"},
			"4.7":  {Title: "确保行级安全已正确配置"},
			"4.8":  {Title: "确保已安装 set_user 扩展"},
			"4.9":  {Title: "确保已安装加密扩展"},
			"4.10": {Title: "确保 public 模式有适当的权限"},
			"5.1":  {Title: "确保本地连接配置正确"},
			"5.2":  {Title: "确保 listen_addresses 配置正确"},
			"5.3":  {Title: "确保本地连接使用安全认证"},
			"5.4":  {Title: "确保主机连接使用安全认证"},
			"5.5":  {Title: "确保已配置连接限制"},
			"5.6":  {Title: "确保已配置密码复杂度验证"},
			"5.7":  {Title: "确保已配置认证超时和延迟"},
			"5.8":  {Title: "确保所有主机连接使用 SSL/GSSENC"},
			"5.9":  {Title: "确保网络 CIDR 范围最小化"},
			"5.10": {Title: "确保指定了特定的数据库和用户"},
			"5.11": {Title: "确保超级用户连接受限"},
			"5.12": {Title: "确保密码加密设置为 scram-sha-256"},
			"6.2":  {Title: "确保 'backend' 运行时参数配置正确"},
			"6.3":  {Title: "确保 'postmaster' 运行时参数配置正确", Manual: true},
			"6.4":  {Title: "确保 'sighup' 运行时参数配置正确", Manual: true},
			"6.5":  {Title: "确保 'superuser' 运行时参数配置正确", Manual: true},
			"6.6":  {Title: "确保 'user' 运行时参数配置正确", Manual: true},
			"6.7":  {Title: "确保使用 FIPS 140-2 加密"},
			"6.8":  {Title: "确保 TLS 已启用并正确配置"},
			"6.9":  {Title: "确保已安装加密扩展"},
			"6.10": {Title: "确保 SSL 密码套件配置正确"},
			"6.11": {Title: "确保已配置数据匿名化扩展"},
			"7.1":  {Title: "确保已配置仅用于复制的用户"},
			"7.2":  {Title: "确保已记录复制命令"},
			"7.4":  {Title: "确保已配置 WAL 归档"},
			"7.5":  {Title: "确保流复制参数配置正确"},
			"8.2":  {Title: "确保已配置备份和恢复工具"},
			"8.3":  {Title: "确保已审查特殊文件和程序配置"},
		},
	})
}
